/* Mechanism node and edge kinds: the vocabulary the BSP entity semantics
 * use to describe doors, buttons, lifts, trains, and teleports and what
 * links them.  Host binding; the RUNE's own mechanism records come later. */
#ifndef SG_MECHANISM_KINDS_H
#define SG_MECHANISM_KINDS_H

typedef enum sg_mech_node_kind_e
{
	SG_MECH_NODE_TRIGGER = 1,
	SG_MECH_NODE_BUTTON = 2,
	SG_MECH_NODE_RELAY = 3,
	SG_MECH_NODE_DOOR_MASTER = 4,
	SG_MECH_NODE_DOOR_MEMBER = 5,
	SG_MECH_NODE_AUTO_DOOR_TRIGGER = 6,
	SG_MECH_NODE_PLATFORM = 7,
	SG_MECH_NODE_PLATFORM_TRIGGER = 8,
	SG_MECH_NODE_TRAIN = 9,
	SG_MECH_NODE_PATH_CORNER = 10,
	SG_MECH_NODE_ELEVATOR = 11,
	SG_MECH_NODE_PUSH = 12,
	SG_MECH_NODE_TELEPORTER = 13,
	SG_MECH_NODE_TELEPORT_TRIGGER = 14,
	SG_MECH_NODE_TELEPORT_DEST = 15,
	SG_MECH_NODE_OBJECTIVE = 16,
	SG_MECH_NODE_SECRET_DOOR = 17,
	SG_MECH_NODE_OTHER_TRIGGER = 18,
	SG_MECH_NODE_OTHER_MOVER = 19,
	SG_MECH_NODE_CONTEXTUAL = 20,
	SG_MECH_NODE_TARGET_SPEAKER = 21,
	SG_MECH_NODE_AREAPORTAL = 22,
	SG_MECH_NODE_TOGGLE_WALL = 23,
	SG_MECH_NODE_TRIGGER_HURT = 24,
	SG_MECH_NODE_TARGET_LASER = 25
} sg_mech_node_kind_t;

typedef enum sg_mech_edge_kind_e
{
	SG_MECH_EDGE_TARGET = 1,
	SG_MECH_EDGE_KILLTARGET = 2,
	SG_MECH_EDGE_OWNER = 3,
	SG_MECH_EDGE_TEAM = 4,
	SG_MECH_EDGE_PATH_TARGET = 5,
	SG_MECH_EDGE_MOVE_TARGET = 6,
	SG_MECH_EDGE_TARGET_ENT = 7,
	SG_MECH_EDGE_ENEMY = 8,
	SG_MECH_EDGE_ROUTE_TARGET = 9
} sg_mech_edge_kind_t;

#endif /* SG_MECHANISM_KINDS_H */
