/* Public result vocabulary for the sealed live tactic execution owner. */
#ifndef SG_TACTIC_EXECUTION_OWNER_H
#define SG_TACTIC_EXECUTION_OWNER_H

#include <stdint.h>

#define SG_TACTIC_EXECUTION_TOKEN_BYTES 16U

/* This value is a one-use capability. Its bytes have no caller-visible
 * meaning and are never accepted as a command, target, or model index. */
typedef struct sg_tactic_execution_token_s
{
	uint8_t opaque[SG_TACTIC_EXECUTION_TOKEN_BYTES];
} sg_tactic_execution_token_t;

typedef enum sg_tactic_execution_owner_status_e
{
	SG_TACTIC_EXECUTION_OWNER_OK = 0,
	SG_TACTIC_EXECUTION_OWNER_INVALID_ARGUMENT,
	SG_TACTIC_EXECUTION_OWNER_ALLOCATION_REJECTED,
	SG_TACTIC_EXECUTION_OWNER_ENTROPY_REJECTED,
	SG_TACTIC_EXECUTION_OWNER_BUSY,
	SG_TACTIC_EXECUTION_OWNER_EMPTY,
	SG_TACTIC_EXECUTION_OWNER_TOKEN_REJECTED,
	SG_TACTIC_EXECUTION_OWNER_PREPARE_REJECTED,
	SG_TACTIC_EXECUTION_OWNER_WITNESS_INCOMPLETE,
	SG_TACTIC_EXECUTION_OWNER_NOT_CURRENT,
	SG_TACTIC_EXECUTION_OWNER_ACTION_REJECTED,
	SG_TACTIC_EXECUTION_OWNER_LOST,
	SG_TACTIC_EXECUTION_OWNER_STATUS_COUNT
} sg_tactic_execution_owner_status_t;

typedef enum sg_tactic_execution_diagnostic_family_e
{
	SG_TACTIC_EXECUTION_DIAGNOSTIC_NONE = 0,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_OWNER,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_RUNTIME,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_PROVIDER,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_STRATEGY,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_LOCALIZATION,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_FIELD,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_SUBJECT,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_HOST,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_STANCE,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_PMOVE,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_HOOK,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_MECHANISM,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_ANGULAR_MOVER,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_ROCKET_JUMP,
	SG_TACTIC_EXECUTION_DIAGNOSTIC_FAMILY_COUNT
} sg_tactic_execution_diagnostic_family_t;

typedef enum sg_tactic_execution_diagnostic_reason_e
{
	SG_TACTIC_EXECUTION_REASON_NONE = 0,
	SG_TACTIC_EXECUTION_REASON_ARGUMENT,
	SG_TACTIC_EXECUTION_REASON_ALLOCATION,
	SG_TACTIC_EXECUTION_REASON_ENTROPY,
	SG_TACTIC_EXECUTION_REASON_OCCUPIED,
	SG_TACTIC_EXECUTION_REASON_EMPTY,
	SG_TACTIC_EXECUTION_REASON_TOKEN,
	SG_TACTIC_EXECUTION_REASON_RUNTIME,
	SG_TACTIC_EXECUTION_REASON_PROVIDER,
	SG_TACTIC_EXECUTION_REASON_STRATEGY,
	SG_TACTIC_EXECUTION_REASON_LOCALIZATION,
	SG_TACTIC_EXECUTION_REASON_FIELD_HANDLE,
	SG_TACTIC_EXECUTION_REASON_SUBJECT_LIFE,
	SG_TACTIC_EXECUTION_REASON_FRAME,
	SG_TACTIC_EXECUTION_REASON_LIVE_STATE,
	SG_TACTIC_EXECUTION_REASON_WITNESS,
	SG_TACTIC_EXECUTION_REASON_ACTION,
	SG_TACTIC_EXECUTION_REASON_OWNER_LOST,
	SG_TACTIC_EXECUTION_REASON_COUNT
} sg_tactic_execution_diagnostic_reason_t;

/* The digest is for log correlation only. It is never checked as authority
 * and deliberately omits token bytes, commands, targets, and private IDs. */
typedef struct sg_tactic_execution_diagnostic_s
{
	sg_tactic_execution_diagnostic_family_t family;
	sg_tactic_execution_diagnostic_reason_t reason;
	uint64_t digest;
} sg_tactic_execution_diagnostic_t;

#endif /* SG_TACTIC_EXECUTION_OWNER_H */
