/* Numeric weapon facts shared by host fire code and effect profiles. */
#ifndef SG_WEAPON_HOST_CONSTANTS_H
#define SG_WEAPON_HOST_CONSTANTS_H

#define SG_HOST_BLASTER_SPEED 1000
#define SG_HOST_BLASTER_DM_DAMAGE 15
#define SG_HOST_BLASTER_NON_DM_DAMAGE 10
#define SG_HOST_BLASTER_LIFETIME_SECONDS 2
#define SG_HOST_BLASTER_BALANCED_LIFETIME_SECONDS 4
#define SG_HOST_BLASTER_BALANCED_HALF_EXTENT 8
#define SG_HOST_HYPERBLASTER_SPEED SG_HOST_BLASTER_SPEED
#define SG_HOST_HYPERBLASTER_DM_DAMAGE 15
#define SG_HOST_HYPERBLASTER_NON_DM_DAMAGE 20
#define SG_HOST_HYPERBLASTER_BALANCED_DAMAGE 12

#define SG_HOST_GRENADE_SPEED 600
#define SG_HOST_GRENADE_VERTICAL_SPEED 200
#define SG_HOST_GRENADE_JITTER 10
#define SG_HOST_GRENADE_DAMAGE 120
#define SG_HOST_GRENADE_RADIUS_BONUS 40
#define SG_HOST_GRENADE_FUSE_MS 2500
#define SG_HOST_GRENADE_FUSE_SECONDS (SG_HOST_GRENADE_FUSE_MS / 1000.0)
#define SG_HOST_GRENADE_BALANCED_DAMAGE_DELTA 10
#define SG_HOST_GRENADE_BALANCED_RADIUS_SCALE 1.5
#define SG_HOST_HAND_GRENADE_DAMAGE 125
#define SG_HOST_HAND_GRENADE_MIN_SPEED 400
#define SG_HOST_HAND_GRENADE_MAX_SPEED 800
#define SG_HOST_HAND_GRENADE_COOK_MS 3000U
#define SG_HOST_HAND_GRENADE_HELD_FUSE_MS 3200U

#define SG_HOST_ROCKET_DAMAGE_BASE 100
#define SG_HOST_ROCKET_DAMAGE_RANDOM_SPAN 20.0
#define SG_HOST_ROCKET_SPEED 650
#define SG_HOST_ROCKET_SPLASH_DAMAGE 120
#define SG_HOST_ROCKET_SPLASH_RADIUS 120
#define SG_HOST_ROCKET_BALANCED_SPEED 750
#define SG_HOST_ROCKET_BALANCED_SPLASH_DAMAGE 75
#define SG_HOST_ROCKET_BALANCED_SPLASH_RADIUS 240

#define SG_HOST_BULLET_HORIZONTAL_SPREAD 300
#define SG_HOST_BULLET_VERTICAL_SPREAD 500
#define SG_HOST_SHOTGUN_HORIZONTAL_SPREAD 1000
#define SG_HOST_SHOTGUN_VERTICAL_SPREAD 500
#define SG_HOST_SHOTGUN_PELLETS 12
#define SG_HOST_SUPER_SHOTGUN_PELLETS 20
#define SG_HOST_SHOTGUN_DAMAGE 4
#define SG_HOST_SHOTGUN_LIVE_HORIZONTAL_SPREAD 500
#define SG_HOST_SHOTGUN_LIVE_VERTICAL_SPREAD 500
#define SG_HOST_SHOTGUN_BALANCED_DAMAGE_DELTA 1
#define SG_HOST_SHOTGUN_BALANCED_PELLET_DELTA 2
#define SG_HOST_SUPER_SHOTGUN_DAMAGE 6
#define SG_HOST_SUPER_SHOTGUN_YAW_DEGREES 5
#define SG_HOST_SUPER_SHOTGUN_BALANCED_DAMAGE_DELTA 3
#define SG_HOST_SUPER_SHOTGUN_BALANCED_PELLET_DELTA 12
#define SG_HOST_MACHINEGUN_DAMAGE 8
#define SG_HOST_MACHINEGUN_BALANCED_DAMAGE 9
#define SG_HOST_MACHINEGUN_BALANCED_SPREAD_DELTA 100
#define SG_HOST_CHAINGUN_DM_DAMAGE 6
#define SG_HOST_CHAINGUN_NON_DM_DAMAGE 8

#define SG_HOST_RAILGUN_DM_DAMAGE 100
#define SG_HOST_RAILGUN_BALANCED_DAMAGE 82
#define SG_HOST_RAILGUN_MATCH_DAMAGE 5000
#define SG_HOST_RAILGUN_NON_DM_DAMAGE 150
#define SG_HOST_RAILGUN_AUXILIARY_TRACE_COUNT 4
#define SG_HOST_RAILGUN_AUXILIARY_DAMAGE 4
#define SG_HOST_RAILGUN_AUXILIARY_SPREAD 512

#define SG_HOST_BFG_SPEED 400
#define SG_HOST_BFG_BALANCED_SPEED 180
#define SG_HOST_BFG_DAMAGE 200
#define SG_HOST_BFG_BALANCED_DAMAGE 180
#define SG_HOST_BFG_CORE_RADIUS 100
#define SG_HOST_BFG_EFFECT_RADIUS 1000
#define SG_HOST_BFG_BALANCED_EFFECT_RADIUS 1200
#define SG_HOST_BFG_PERIODIC_RAY_DAMAGE 5
#define SG_HOST_BFG_NON_DM_DAMAGE 500
#define SG_HOST_BFG_NON_DM_PERIODIC_RAY_DAMAGE 10
#define SG_HOST_BFG_BALANCED_PERIODIC_RAY_DAMAGE 3
#define SG_HOST_BFG_PERIODIC_RAY_RADIUS 256
#define SG_HOST_BFG_PERIODIC_RAY_DISTANCE 2048
#define SG_HOST_BFG_FLASH_FRAME 9
#define SG_HOST_BFG_FIRE_FRAME 17
#define SG_HOST_BFG_AMMO_COST 50

#define SG_HOST_DAMAGE_QUAD_SCALE 4
#define SG_HOST_RADIUS_SELF_SCALE 0.5

/* T_Damage momentum: velocity += dir * scale * knockback / mass, with the
 * self-hit scale being what makes rocket jumps work.  Splash damage falls off
 * as damage - distance/2 from the blast to the target box centre. */
#define SG_HOST_KNOCKBACK_SCALE 500.0
#define SG_HOST_SELF_KNOCKBACK_SCALE 1600.0
#define SG_HOST_BALANCED_KNOCKBACK_SCALE 800.0
#define SG_HOST_BALANCED_SELF_KNOCKBACK_SCALE 1800.0
#define SG_HOST_KNOCKBACK_MIN_MASS 50
#define SG_HOST_SPLASH_DISTANCE_FALLOFF 0.5

/* P_ProjectSource offset for launcher-class weapons: forward, right, and
 * below the view height. */
#define SG_HOST_PROJECTILE_SOURCE_FORWARD 8
#define SG_HOST_PROJECTILE_SOURCE_RIGHT 8
#define SG_HOST_PROJECTILE_SOURCE_BELOW_VIEW 8

/* CheckArmor: save = ceil(protection * damage), capped by the armor count. */
#define SG_HOST_ARMOR_JACKET_PROTECTION 0.30
#define SG_HOST_ARMOR_COMBAT_PROTECTION 0.60
#define SG_HOST_ARMOR_BODY_PROTECTION 0.80
#define SG_HOST_WEAPON_RAY_DISTANCE 8192
#define SG_HOST_PROJECTILE_RETIRE_DISTANCE 8000
#define SG_HOST_SERVER_FRAME_MS 100
#define SG_HOST_BFG_WINDUP_MS \
	((SG_HOST_BFG_FIRE_FRAME - SG_HOST_BFG_FLASH_FRAME) * \
	 SG_HOST_SERVER_FRAME_MS)

#define SG_HOST_HOOK_FIRE_SPEED 800
#define SG_HOST_HOOK_PULL_SPEED 800
#define SG_HOST_HOOK_INITIAL_DAMAGE 8
#define SG_HOST_HOOK_ATTACHED_DAMAGE 1
#define SG_HOST_HOOK_HEALTH 59

#endif /* SG_WEAPON_HOST_CONSTANTS_H */
